// Frozen rule registry — the machine-readable form of §3 of the
// Gate 3 plan. Every rule follows a fixed shape; the meta-schema in
// __tests__/rules.test.js enforces it. Consumers reference rules by
// ruleId; the human-facing messages live in messages.js.

/**
 * @typedef {"blocking"|"warning"|"informational"} Severity
 * @typedef {"field"|"entity"|"cross-entity"|"output"} Scope
 */

/**
 * @typedef {Object} Rule
 * @property {string} ruleId
 * @property {Severity} severity
 * @property {Scope} scope
 * @property {string[]} target
 * @property {string} messageTemplate
 * @property {Object} metadataTemplate
 * @property {"drafting"|"export"|"approval"|null} phase
 */

/** @type {Rule[]} */
const RULES = [
  // ── §2.1 numeric ranges ─────────────────────────────────────────
  { ruleId: "mcat.total.range", severity: "blocking", scope: "field",
    target: ["mcat.totalScore"],
    messageTemplate: "MCAT total must be between {totalMin} and {totalMax}.",
    metadataTemplate: { totalMin: 472, totalMax: 528 }, phase: null },
  { ruleId: "mcat.section.range", severity: "blocking", scope: "field",
    target: ["mcat.cpbsScore", "mcat.carsScore", "mcat.bbfnScore", "mcat.psbbScore"],
    messageTemplate: "Each MCAT section score must be between {sectionMin} and {sectionMax}.",
    metadataTemplate: { sectionMin: 118, sectionMax: 132 }, phase: null },
  { ruleId: "mcat.sum-mismatch", severity: "blocking", scope: "cross-entity",
    target: ["mcat"],
    messageTemplate: "MCAT total ({total}) must equal the sum of the four section scores ({sum}).",
    metadataTemplate: { total: 0, sum: 0 }, phase: null },
  { ruleId: "mcat.date.stale", severity: "warning", scope: "field",
    target: ["mcat.testDate"],
    messageTemplate: "MCAT scores older than {validityYears} years may not be accepted by some schools you are applying to.",
    metadataTemplate: { validityYears: 4 }, phase: null },
  { ruleId: "mcat.attempts.exceeded", severity: "blocking", scope: "entity",
    target: ["applicantMcatAttempts"],
    messageTemplate: "AAMC lifetime cap is {lifetimeAttemptCap} attempts. Remove or void an earlier attempt.",
    metadataTemplate: { lifetimeAttemptCap: 4 }, phase: null },
  { ruleId: "mcat.voided.contradiction", severity: "blocking", scope: "entity",
    target: ["mcat"],
    messageTemplate: "A voided attempt cannot have section scores.",
    metadataTemplate: {}, phase: null },
  { ruleId: "preview.range", severity: "blocking", scope: "field",
    target: ["preview.score"],
    messageTemplate: "AAMC PREview score must be between {min} and {max}.",
    metadataTemplate: { min: 1, max: 9 }, phase: null },
  { ruleId: "gpa.range", severity: "blocking", scope: "field",
    target: ["metrics.cumulativeGPA"],
    messageTemplate: "GPA must be between {min} and {max}.",
    metadataTemplate: { min: 0.0, max: 4.0 }, phase: null },
  { ruleId: "gpa.sgpa.range", severity: "blocking", scope: "field",
    target: ["metrics.scienceGPA"],
    messageTemplate: "Science GPA (BCPM) must be between {min} and {max}.",
    metadataTemplate: { min: 0.0, max: 4.0 }, phase: null },
  { ruleId: "experience.hours.negative", severity: "blocking", scope: "field",
    target: ["experienceHours.hoursTotal"],
    messageTemplate: "Total hours cannot be negative.",
    metadataTemplate: {}, phase: null },
  { ruleId: "experience.hours.ceiling", severity: "blocking", scope: "field",
    target: ["experienceHours.hoursTotal"],
    messageTemplate: "Total hours over {ceiling} is not accepted.",
    metadataTemplate: { ceiling: 100000 }, phase: null },
  { ruleId: "experience.hours.year-sum", severity: "blocking", scope: "cross-entity",
    target: ["experienceHours"],
    messageTemplate: "Yearly hours ({sum}) do not match total ({total}).",
    metadataTemplate: { sum: 0, total: 0 }, phase: null },
  { ruleId: "activity.description.limit", severity: "blocking", scope: "field",
    target: ["activity.description"],
    messageTemplate: "Activity description exceeds the {limit}-character AMCAS limit ({current}/{limit}).",
    metadataTemplate: { limit: 700, current: 0 }, phase: "export" },
  { ruleId: "activity.mostMeaningful.essay.limit", severity: "blocking", scope: "field",
    target: ["activity.mostMeaningfulEssay"],
    messageTemplate: "Most-meaningful essay exceeds the {limit}-character AMCAS limit ({current}/{limit}).",
    metadataTemplate: { limit: 1325, current: 0 }, phase: "export" },
  { ruleId: "activity.mostMeaningful.cap", severity: "blocking", scope: "entity",
    target: ["applicantActivities"],
    messageTemplate: "You may mark at most {cap} activities as most meaningful.",
    metadataTemplate: { cap: 3 }, phase: null },
  { ruleId: "activity.count.cap", severity: "blocking", scope: "entity",
    target: ["applicantActivities"],
    messageTemplate: "AMCAS allows at most {cap} activities.",
    metadataTemplate: { cap: 15 }, phase: null },
  { ruleId: "schoolList.count.cap", severity: "blocking", scope: "entity",
    target: ["applicantSchoolList"],
    messageTemplate: "School list has {n} entries — please reduce to at most {cap}.",
    metadataTemplate: { cap: 40, n: 0 }, phase: "export" },

  // ── §2.2 references / cross-entity ──────────────────────────────
  { ruleId: "prompt.school.orphan", severity: "blocking", scope: "cross-entity",
    target: ["secondaryPrompt.schoolId"],
    messageTemplate: "This prompt references a school that is not in your school list.",
    metadataTemplate: {}, phase: null },
  { ruleId: "interpretation.axis.mismatch", severity: "blocking", scope: "cross-entity",
    target: ["promptInterpretation.keyAxes"],
    messageTemplate: "This interpretation lists an axis ({axis}) that isn't part of the school's fit axes.",
    metadataTemplate: { axis: "" }, phase: null },
  { ruleId: "research.citations.missing", severity: "blocking", scope: "entity",
    target: ["schoolResearch.citationRefs"],
    messageTemplate: "Each school must include at least one citation before school-fit matching can run.",
    metadataTemplate: {}, phase: null },
  { ruleId: "prompt.source-citation.missing", severity: "blocking", scope: "field",
    target: ["secondaryPrompt.sourceCitationId"],
    messageTemplate: "Each secondary prompt must reference a citation proving where the prompt was retrieved.",
    metadataTemplate: {}, phase: null },
  { ruleId: "draft.evidence.missing", severity: "blocking", scope: "output",
    target: ["draft.evidenceCitations"],
    messageTemplate: "Draft must cite at least one evidence item before it can be exported.",
    metadataTemplate: {}, phase: "export" },
  { ruleId: "draft.school-claim.agent-uncited", severity: "blocking", scope: "output",
    target: ["draft.sentenceIndex"],
    messageTemplate: "Agent-generated school claim needs a matching school citation.",
    metadataTemplate: {}, phase: null },
  { ruleId: "draft.school-claim.applicant-uncited", severity: "warning", scope: "output",
    target: ["draft.sentenceIndex"],
    messageTemplate: "Consider adding a citation for this school-specific note.",
    metadataTemplate: {}, phase: null },
  { ruleId: "draft.evidence.unconfirmed", severity: "blocking", scope: "output",
    target: ["draft.evidenceCitations"],
    messageTemplate: "This evidence item is marked unconfirmed, so it cannot be used in a draft yet.",
    metadataTemplate: {}, phase: null },
  { ruleId: "draft.evidence.orphan", severity: "blocking", scope: "output",
    target: ["draft.evidenceCitations"],
    messageTemplate: "Draft cites an evidence ID that no longer exists in your bank.",
    metadataTemplate: {}, phase: null },
  { ruleId: "draft.citation.orphan", severity: "blocking", scope: "output",
    target: ["draft.schoolCitations"],
    messageTemplate: "Draft cites a school-citation ID that no longer exists.",
    metadataTemplate: {}, phase: null },
  { ruleId: "interview.stories.min", severity: "warning", scope: "entity",
    target: ["interviewPrepInputs.storyIds"],
    messageTemplate: "We recommend prepping at least {min} stories per school.",
    metadataTemplate: { min: 3 }, phase: null },
  { ruleId: "evidence.activity.orphan", severity: "blocking", scope: "cross-entity",
    target: ["evidenceItem.activityLinks"],
    messageTemplate: "This evidence links to an activity that no longer exists.",
    metadataTemplate: {}, phase: null },
  { ruleId: "doNotUseTopics.scope.orphan", severity: "blocking", scope: "cross-entity",
    target: ["doNotUseTopic.scopedSchoolIds"],
    messageTemplate: "This do-not-use topic is scoped to a school not in your list.",
    metadataTemplate: {}, phase: null },

  // ── §2.3 freshness ──────────────────────────────────────────────
  { ruleId: "research.stale", severity: "warning", scope: "entity",
    target: ["schoolResearch.updatedAt"],
    messageTemplate: "School research for {schoolName} was last updated {n} days ago. Refresh before running current-cycle steps.",
    metadataTemplate: { schoolName: "", n: 0 }, phase: null },
  { ruleId: "research.stale.currentCycleBlock", severity: "blocking", scope: "entity",
    target: ["schoolResearch"],
    messageTemplate: "School research is required for a current-cycle deadline and is stale or uncited — refresh before continuing.",
    metadataTemplate: {}, phase: null },
  { ruleId: "prompt.stale", severity: "warning", scope: "field",
    target: ["secondaryPrompt.retrievedAt"],
    messageTemplate: "This prompt was retrieved {n} days ago — verify the school still uses this wording.",
    metadataTemplate: { n: 0 }, phase: null },
  { ruleId: "prompt.stale.uncited", severity: "blocking", scope: "entity",
    target: ["secondaryPrompt"],
    messageTemplate: "This prompt has no source citation and is older than {threshold} days — add a citation or re-retrieve.",
    metadataTemplate: { threshold: 60 }, phase: null },
  { ruleId: "citation.stale", severity: "informational", scope: "field",
    target: ["citation.retrievedAt"],
    messageTemplate: "Citation is older than 12 months.",
    metadataTemplate: {}, phase: null },
  { ruleId: "citation.stale.currentCycleBlock", severity: "blocking", scope: "entity",
    target: ["citation"],
    messageTemplate: "Citation used for a current-cycle requirement is over 12 months old — replace or reconfirm.",
    metadataTemplate: {}, phase: null },

  // ── §2.4 draft output rules ─────────────────────────────────────
  { ruleId: "draft.claim.uncited", severity: "blocking", scope: "output",
    target: ["draft.sentenceIndex"],
    messageTemplate: "This applicant claim is not tied to any evidence ID.",
    metadataTemplate: {}, phase: null },
  { ruleId: "draft.doNotUseTopics.hit", severity: "blocking", scope: "output",
    target: ["draft.draftText"],
    messageTemplate: "Draft contains language matching a do-not-use topic: \"{topicKey}\".",
    metadataTemplate: { topicKey: "" }, phase: null },
  { ruleId: "draft.placeholder.third-person", severity: "blocking", scope: "output",
    target: ["draft.draftText"],
    messageTemplate: "Draft contains \"the applicant\" / \"fictional applicant\" / placeholder text — this must be rewritten in first person.",
    metadataTemplate: {}, phase: null },
  { ruleId: "draft.copied-evidence", severity: "warning", scope: "output",
    target: ["draft.draftText"],
    messageTemplate: "Draft contains text copied verbatim from an evidence item — rewrite in your own words.",
    metadataTemplate: {}, phase: "drafting" },
  { ruleId: "draft.copied-evidence.export-block", severity: "blocking", scope: "output",
    target: ["draft.draftText"],
    messageTemplate: "Draft still contains copied evidence text — resolve before export or approval.",
    metadataTemplate: {}, phase: "approval" },
  { ruleId: "draft.wordLimit.exceeded", severity: "blocking", scope: "output",
    target: ["draft.wordCount"],
    messageTemplate: "Draft is {n} words over the {limit}-word prompt limit.",
    metadataTemplate: { n: 0, limit: 0 }, phase: "export" },
  { ruleId: "draft.charLimit.exceeded", severity: "blocking", scope: "output",
    target: ["draft.charCount"],
    messageTemplate: "Draft is {n} characters over the {limit}-character prompt limit.",
    metadataTemplate: { n: 0, limit: 0 }, phase: "export" },
  { ruleId: "draft.underfilled", severity: "warning", scope: "output",
    target: ["draft.wordCount"],
    messageTemplate: "Draft is only {pct}% of the available length — consider adding depth.",
    metadataTemplate: { pct: 0 }, phase: null },
  { ruleId: "draft.repeated-story", severity: "warning", scope: "output",
    target: ["draft.evidenceCitations"],
    messageTemplate: "You have used this evidence in {n} other drafts already this cycle.",
    metadataTemplate: { n: 0 }, phase: null },
  { ruleId: "draft.generic-fit", severity: "warning", scope: "output",
    target: ["draft.draftText"],
    messageTemplate: "The school-fit language reads generic — cite a specific program, faculty, or curricular feature.",
    metadataTemplate: {}, phase: null },
  { ruleId: "draft.interview-defensibility.unconfirmed-sensitive", severity: "blocking", scope: "output",
    target: ["draft.sentenceIndex"],
    messageTemplate: "Draft uses unconfirmed or sensitive evidence — confirm before applicant-facing review.",
    metadataTemplate: {}, phase: "approval" },
  { ruleId: "draft.interview-defensibility.thin", severity: "warning", scope: "output",
    target: ["draft.sentenceIndex"],
    messageTemplate: "This claim is supported but thin — add depth for interview defensibility.",
    metadataTemplate: {}, phase: null },

  // ── §2.5 sensitivity ────────────────────────────────────────────
  { ruleId: "evidence.sensitivity.unconfirmed", severity: "warning", scope: "entity",
    target: ["evidenceItem"],
    messageTemplate: "This evidence has a sensitivity tag ({tag}) — please confirm before allowing it in drafts.",
    metadataTemplate: { tag: "" }, phase: null },
  { ruleId: "evidence.sensitivity.patient-info", severity: "blocking", scope: "entity",
    target: ["evidenceItem"],
    messageTemplate: "This evidence appears to contain patient-identifiable information. Please redact before continuing.",
    metadataTemplate: {}, phase: null },
];

const RULES_BY_ID = Object.fromEntries(RULES.map((r) => [r.ruleId, r]));

export const rules = Object.freeze(RULES.map((r) => Object.freeze({ ...r })));
export const rulesById = Object.freeze(RULES_BY_ID);
export function getRule(ruleId) {
  return rulesById[ruleId] || null;
}
